### ISSUE TITLE
koordinates-create-token: error: too few arguments

### ISSUE THREAD

**Issue by palmerj** [koordinates/python-client#11]
I get the following error when trying to allocate an api key with the koordinates-create-token tool when using the "--scopes" optional parameter

koordinates-create-token data.linz.govt.nz xxx@xxx.xom --scopes layers:read test_token_api
usage: koordinates-create-token [-h] [--scopes SCOPE [SCOPE ...]]
                                [--referrers HOST [HOST ...]] [--expires DATE]
                                SITE EMAIL NAME
koordinates-create-token: error: too few arguments

I'm running Python 2.7.10 on MacOSX 10.10

**Comment by hamishcampbell** [comment]
Hi Jeremy,

It should work like so:

```koordinates-create-token data.linz.govt.nz xxx@xxx.xom --scopes=layers:read test_token_api```

**Comment by palmerj** [comment]
Oh thanks. Can the command line synopsis please be update to state that the '=' character is required for the option?
