### ISSUE TITLE
Error with Client.request 

### ISSUE THREAD

**Issue by josephramsay** [koordinates/python-client#12]
Hi Kx,
Getting an error connecting to linz at "data.linz.govt.nz" in function _raw_request(self, method, url, headers, *args, **kwargs):

for context: 
method = u'GET'
url = 'https://data.linz.govt.nz/services/api/v1/layers/'
headers = {'Accept': 'application/json', 'Authorization': 'key [apikey]'}
args = ()
kwargs = {}

problem is the request response "r" has no attr r.reason (though there is an attr r.raw.reason)
NB. resp is auth error, r.status_code = 401 and r.elapsed not exists 

maybe a problem with requests version?

'''
Traceback (most recent call last):
  File "/home/[user]/git/<wrapper.py>", line 26, in <module>
    class LayerDispatch(object):
  File "/home/[user]/git/<wrapper.py>", line 28, in LayerDispatch
    for layer in c.layers.list():
  File "/usr/local/lib/python2.7/dist-packages/koordinates-0.2.0-py2.7.egg/koordinates/base.py", line 170, in __iter__
    r = self._request(url)
  File "/usr/local/lib/python2.7/dist-packages/koordinates-0.2.0-py2.7.egg/koordinates/base.py", line 115, in _request
    r = self._manager.client.request(method, url, headers=self._to_headers())
  File "/usr/local/lib/python2.7/dist-packages/koordinates-0.2.0-py2.7.egg/koordinates/client.py", line 112, in request
    r = self._raw_request(method, url, headers, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/koordinates-0.2.0-py2.7.egg/koordinates/client.py", line 137, in _raw_request
    logger.info('Response: %d %s in %s', r.status_code, r.reason, r.elapsed)
AttributeError: 'Response' object has no attribute 'reason'
'''

**Comment by rcoup** [comment]
Are you using requests >= v2? (looks like `Response.reason` has existed since [since v0.13.2](https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#0132-2012-06-28). `setup.py` has it as part of `install_requires`, so it should have stopped the install if it wasn't available.

**Comment by josephramsay** [comment]
Didn't get an install_requires failure and am at the latest python-requests for precise, <v2.

~$ apt-cache policy python-requests
python-requests:
  Installed: 0.8.2-1
  Candidate: 0.8.2-1
  Version table:
 *** 0.8.2-1 0
        500 http://nz.archive.ubuntu.com/ubuntu/ precise/universe amd64 Packages
        100 /var/lib/dpkg/status
~$ sudo apt-get install python-requests
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-requests is already the newest version.
~$ uname -a
Linux LZ104588U 3.8.0-44-generic #66~precise1-Ubuntu SMP Tue Jul 15 04:01:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rcoup** [comment]
You need to run it in a virtualenv environment, requests 0.8.2 won't cut it unfortunately - we're using a bunch of features in requests (& other libraries) that need reasonably up-to-date versions.
