### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by josephramsay** [koordinates/python-client#14]
Unable to authenticate using LDS API key.

Running the simple script

```python
import koordinates

lclient = koordinates.Client(host='data.linz.govt.nz', token='\<linz-api-key\>')
print lclient

for layer in lclient.layers.order_by('created_at')[:10]:
   print(layer)

for layer in lclient.catalog.list().filter(license__type='cc').filter(type='layer').order_by('created_at'):
        print(layer.title)
```

produces the trace

```
<koordinates.client.Client object at 0x7f3d59eb3fd0>
No handlers could be found for logger "koordinates.client"
Traceback (most recent call last):
  File "Test.py", line 6, in <module>
    for layer in lclient.layers.order_by('created_at')[:10]:
  File "/usr/local/lib/python2.7/dist-packages/koordinates/base.py", line 216, in __getitem__
    return list(itertools.islice(self.__iter__(), k.stop))
  File "/usr/local/lib/python2.7/dist-packages/koordinates/base.py", line 170, in __iter__
    r = self._request(url)
  File "/usr/local/lib/python2.7/dist-packages/koordinates/base.py", line 115, in _request
    r = self._manager.client.request(method, url, headers=self._to_headers())
  File "/usr/local/lib/python2.7/dist-packages/koordinates/client.py", line 112, in request
    r = self._raw_request(method, url, headers, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/koordinates/client.py", line 143, in _raw_request
    raise exceptions.ServerError.from_requests_error(e)
koordinates.exceptions.AuthenticationError: 401 Client Error: UNAUTHORIZED
```

**Comment by hamishcampbell** [comment]
Hi Joseph,

Do you get a `OAuth-Scopes` header in responses, and what does it contain?

**Comment by josephramsay** [comment]
Hi Hamish, 
No 0Auth-Scopes that I can see
>>> k=koordinates.Client(host='data.linz.govt.nz', token='\<linz-api-key\>')
>>> r=k.request('POST','http://data.linz.govt.nz')
<Response [200]>
>>> r.headers
{'content-language': 'en-GB', 'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'set-cookie': 'csrftoken=LxSTkU6BePS0egAGQn8I5FKJEVscFLKZ; expires=Mon, 24-Oct-2016 22:25:54 GMT; Max-Age=31449600; Path=/; secure', 'vary': 'Accept-Encoding, Cookie,Accept-Language,Accept-Encoding, User-Agent', 'server': 'Koordinates', 'x-k-gentime': '0.908', 'connection': 'keep-alive', 'date': 'Mon, 26 Oct 2015 22:25:54 GMT', 'content-type': 'text/html; charset=utf-8'}

**Comment by hamishcampbell** [comment]
Could you let me know the owner and last two characters of the key. I'll look it up from there.

**Comment by josephramsay** [comment]
Under my account. For the above result I was using the key I call 'turkey', ending with 2b, but I've tried them all, each with the same result. NB both 'monkey' (e2) and 'turkey' (2b) were created using the API

**Comment by hamishcampbell** [comment]
Hey Joseph,

The token _turkey_ has the scopes:

```catalog query tiles wxs:wcs wxs:wfs wxs:wms```

Problem here is as soon as you want to look at the layer detail you _also_ need the scope `layer:read`. Add that and you should be fine.

**Comment by josephramsay** [comment]
Thanks Hamish, FYI layer[s]:read
