### ISSUE TITLE
Metadata posts raise exception when 204 not return 

### ISSUE THREAD

**Issue by SPlanzer** [koordinates/python-client#27]
As per the below, When making a metadata post request via the python client an exception is raised each time. This is because the set method ensures all responses are of the 204 status code. The actual response returned is a 200. This also an issue as data has been created and a 201 would be desirable. 

This [gist](https://gist.github.com/SPlanzer/c3409c77a8e0399565009bf23b692214) can be used to see a 200 is returned  

https://github.com/koordinates/python-client/blob/e0a6f9e80b5aba4584771d976c15b6711c39b221/koordinates/metadata.py#L34-L35

**Comment by hamishcampbell** [comment]
@SPlanzer -- fixes for this and #26 have been merged to master. Are you able to test from source?

**Comment by SPlanzer** [comment]
@hamishcampbell - Thanks a lot. I will test from source.

**Comment by SPlanzer** [comment]
Thanks @hamishcampbell  Changes are exactly as I expect. - Closed
