### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by craigds** [koordinates/python-client#34]
Supporting python 2 these days is unnecessary and is just holding back better code style.

Let's drop everything below ~3.6?

**Comment by rcoup** [comment]
👍 

We should pick the lowest that's easiest to support. Py3.5 is still supported upstream until September 2020, so that's probably a maximum?

**Comment by craigds** [comment]
3.5 means we can't use f-strings, which is frustrating. 3.6 was released in December 2016. Do you think there are people using this library who are still on <3.6?

**Comment by rcoup** [comment]
More about distributions builtin/bundled Python versions.

**Comment by craigds** [comment]
debian jessie still has 3.4, and that's LTS supported till June 2020. So... 3.4? It makes me sad but I can live with it :) At least it's not 2.
